jobs:
- job: Job_1
  displayName: Build Images.
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
  - task: PackerTool@0
    displayName: 'Install Packer '
  - task: Packer@1
    displayName: Packer build
    inputs:
      connectedServiceAzure: 
      templatePath: azure_vm.pkr.hcl
      variables-file: variables.pkrvars.hcl
...
